---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: surtr
  namespace: default
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 5
  schedule: 0 10 * * *
  jobTemplate:
    spec:
      template:
        metadata:
        spec:
          serviceAccountName: surtr
          containers:
          - name: surtr
            image: quay.io/uswitch/surtr
            imagePullPolicy: Always
            env:
            - name: AWS_REGION
              value: "eu-west-1"
            args:
            - --older-than=168h
            volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ssl-certs
          volumes:
            - name: ssl-certs
              hostPath:
                path: /usr/share/ca-certificates
          restartPolicy: Never
